### ISSUE TITLE
Hard-coded English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [grabs/moodle-mod_unilabel#10]
Hi,
I think this great plugin would be even greater if some English language strings that are currently hard-coded were changed into string variables, so that they would be available for translation in AMOS.

The strings are:

Carousel
Collapsed text
Course teaser
grid
Simple text
Topic teaser

I am sure many Spanish-speaking (and many other non-English speakers) Moodlers would prefer to have these strings available in their native language.

I hope this improvement will not be too difficult to implement :)
Thanks in advance.

**Comment by grabs** [comment]
Hi Germán, can you point me to the files where you think I have hard coded strings? I am very sure I only use language strings.

**Comment by germanvaleroelizondo** [comment]
You are 100% correct.
My mistake :(
I am afraid I made the mistake of translating only the strings for unilabel.php and I completly forgot about all the unilabeltype_*.php files in AMOS. I will translate them ASAP.
