### ISSUE TITLE
Cannot move unilabel to the right on the main class page

### ISSUE THREAD

**Issue by hartmut1s** [grabs/moodle-mod_unilabel#16]
I cannot move Unilabel to the right on the main class page in Boost theme. Indenting this resource is not yet possible.
![Cannot move unilabel to the right on main class page in Boost theme](https://user-images.githubusercontent.com/8261898/84561788-a3c77180-ad4f-11ea-9175-4dee9ec0b1ed.jpg)

**Comment by grabs** [comment]
Hi Hartmut,
thanks for reporting this!
I fixed it für 38 and 39. With the last version the indentation works fine.
Best regards
Andreas
