### ISSUE TITLE
Bug? Unilabel-Grid with GRID-Format failed

### ISSUE THREAD

**Issue by KarlKarlchen** [grabs/moodle-mod_unilabel#17]
Hello, 
there is a problem when using Unilabel-grid with GRID-Format.
When students click on one of the grid-images, the text is shown correct but dark and there is no possibility to click any Button like close etc.
Before click: ![Bildschirmfoto vom 2020-06-16 19-30-55](https://user-images.githubusercontent.com/67018510/84807707-efa44000-b007-11ea-8795-e7844b461d23.png)
After click: ![Bildschirmfoto vom 2020-06-16 19-29-03](https://user-images.githubusercontent.com/67018510/84807656-dbf8d980-b007-11ea-9165-2148a13411c2.png)

Please help
Karl

**Comment by grabs** [comment]
Hi Karl,
thank you for reporting this! Can you give me some more information about your setup?
- Moodle-Version
- Unilabel-Version
- Browser-Version
Best regards
Andreas

**Comment by KarlKarlchen** [comment]
Hi Andreas,
thanks for answering soon.
I`m using newest MINT-Linux Cinnamon but my students using smartphones tells me the same situation. 
I used Moodle 3.8 and now the newest Moodle 3.9
Moodle: 3.9 (Build: 20200615)
Newest Unilabel: 3.9 2020061001  
With Moodle 3.8 i used adaptable-theme and now moove-theme.
I tested with newest Opera (MINT-Linux) Version:67.0.3575.79 and Firefox (77.0.1 (64-Bit)) and Chrome (Version 83.0.4103.97 (Offizieller Build) (64-Bit))

Thanks for help
Karl

**Comment by grabs** [comment]
Hi Karl,
did you try the default boost theme?
Btw. your moove theme has a newer version. Maybe you should install that instead.
Best regards
Andreas

**Comment by KarlKarlchen** [comment]
Hi Andreas,
the same using boost or classic theme :(
Best regards
Karl

**Comment by grabs** [comment]
Hi Karl,
I'm running out of ideas :(.
Is it possible that you create a course backup without userdata and send it to me?
I could try it out in my environment.
Best regards
Andreas

**Comment by KarlKarlchen** [comment]
Hi Andreas,
It´s only a test course, so i can send it to you. 
[sicherung-moodle2-course-11-ef-2-zn-20200620-2121-an.zip](https://github.com/grabs/moodle-mod_unilabel/files/4808462/sicherung-moodle2-course-11-ef-2-zn-20200620-2121-an.zip)
But it`s a problem with every (new) course. Use grid-theme and unilabel with grids the site freeze when clicking on any grid-image. Everything is ok when switch on editing. I can click on the images, read the text and close normal.
![Bildschirmfoto vom 2020-06-20 21-30-05](https://user-images.githubusercontent.com/67018510/85210082-49c14000-b33d-11ea-89ce-d5bb4d6b1c52.png)
![Bildschirmfoto vom 2020-06-20 21-30-15](https://user-images.githubusercontent.com/67018510/85210085-4d54c700-b33d-11ea-86bf-b027a058a24c.png)

Thanks for help
Karl

**Comment by grabs** [comment]
Hi Karl,
the information about using the format_grid plugin was the key.
There was a problem with the modals started from another modal just like the format_grid plugin has.
I fixed it now and will also put it into the moodle plugin database.
Thanks!
Best regards
Andreas

**Comment by KarlKarlchen** [comment]
Hello Andreas,
everything is fine now :)
Thanks a lot
Karl

**Comment by jesusman111** [comment]
Hello:
I have a similar problem.
The moove theme does not work unilabel.
Neither with the grid format nor with the theme format.
I use moodle 3.8.3
Can you help me?
Thank you very much
Regards
