### ISSUE TITLE
Theme "moove"

### ISSUE THREAD

**Issue by jesusman111** [grabs/moodle-mod_unilabel#18]
Hello:
The moove theme does not work unilabel.
Neither with the grid format nor with the theme format.
I use moodle 3.8.3
Can you help me?
Thank you very much
Regards

**Comment by grabs** [comment]
Hi jesusman111,
I can not reproduce any problem with these plugins.
Did you install the latest version of them?
Best regards

**Comment by jesusman111** [comment]
Yes. I have the latest version installed.
The carousel does not work, nor the links.
I leave a screenshot
Thank you very much
Best regards
![cap-169](https://user-images.githubusercontent.com/61394948/87211225-caf66c00-c318-11ea-8e10-0a96abe1569a.png)

**Comment by grabs** [comment]
Hi,
I am sorry. But I still can't see anything wrong.

I need some more detailed information:
- Version number of Moodle (Build)
- Version number of format_grid
- Version number of theme_moove
- Version number of mod_unilabel
- php version
- database type and version
- What browser do you use

Please provide some steps to see the way how you include the unilabel into your page.

Best regards

**Comment by jesusman111** [comment]
Hi,
These are the data:

Version number of Moodle (Build): 3.8.3+ (Build: 20200515)
Version number of format_grid: 3.8.0.1    2019111700
Version number of theme_moove: 3.8.13    2020062600
Version number of mod_unilabel: 3.8.2  2020022902
php version: 7.4.7
database type and version: mysql (5.7.30-log) | versión  5.7.30

What browser do you use: Chrome and Firefox
Please provide some steps to see the way how you include the unilabel into your page.

![cap-01](https://user-images.githubusercontent.com/61394948/87230025-30943800-c3ad-11ea-939d-cef0546c1cf8.png)
![cap-02](https://user-images.githubusercontent.com/61394948/87230026-312cce80-c3ad-11ea-9372-60df81c04c19.png)
![cap-03](https://user-images.githubusercontent.com/61394948/87230028-31c56500-c3ad-11ea-8e5c-08f97909cfee.png)
![cap-04](https://user-images.githubusercontent.com/61394948/87230030-31c56500-c3ad-11ea-9eb2-f5876ce68a41.png)
![cap-06](https://user-images.githubusercontent.com/61394948/87230031-325dfb80-c3ad-11ea-90ef-7007a9237790.png)
![cap-07](https://user-images.githubusercontent.com/61394948/87230032-325dfb80-c3ad-11ea-82e0-794d9aeb2b88.png)

Thank you so much
Best regards

**Comment by grabs** [comment]
Hm, I tried your setting except the database. All is working fine.
Your screenshots look ok to me.
Can you describe what exactly is not working?

**Comment by jesusman111** [comment]
Carousel does not work.
Neither do the links.
Controls are not shown.
The other utilities of the plugin do not go well either.
It interferes with the course editing menu, causing it to not work well.

Thank you very much
Regards

**Comment by jesusman111** [comment]
I have attached a copy of the course in case it can be of help.

Thanks again
Best regards

[copia_de_seguridad-moodle2-course-10-curso_de_prueba-20200712-0057.zip](https://github.com/grabs/moodle-mod_unilabel/files/4907741/copia_de_seguridad-moodle2-course-10-curso_de_prueba-20200712-0057.zip)

**Comment by grabs** [comment]
On my site all looks fine except the buttons for right and left. But this is a problem of the theme_moove.
You can do a workaround by defining different buttons on the global configuration of the unilabel.
I hope this helps.
![unilabel-carousel](https://user-images.githubusercontent.com/616245/87242400-9ffd3c80-c42c-11ea-80a7-6cee84a9101f.png)
![unilabel-carousel-editmode](https://user-images.githubusercontent.com/616245/87242401-a1c70000-c42c-11ea-96a9-ec09f1d5fb2c.png)

**Comment by jesusman111** [comment]
How can I configure the buttons?
Images do not automatically pass from one to the other. Links don't work either. Could there be a problem with another plugin you have installed?
In addition, with the Chrome browser, the course editing menus are blocked.

Thank you very much again.

**Comment by grabs** [comment]
You can configure the buttons on
Website administration / Plugins / Activity modules / Unilabel
Your links are working fine. But in the example you gave me the urls were defined in a wrong way.
You had "www.google.es" but it must be "https://www.google.es"!
If you have some additional CSS defined for your theme or globally there could be another cause for the links not being working.
Best regards

**Comment by jesusman111** [comment]
I have done what you tell me, but I have not made it work. Neither browsers, nor links, and the carousel ...
Thank you very much for your help
Best regards

![cap-18](https://user-images.githubusercontent.com/61394948/87246973-2166c600-c451-11ea-912b-e8ca718f1aea.png)

**Comment by jesusman111** [comment]
I have done what you tell me, but I have not made it work. Neither browsers, nor links, and the carousel ...
Thank you very much for your help
Best regards
