### ISSUE TITLE
Problem with links under the navigation menu

### ISSUE THREAD

**Issue by ralf-krause** [grabs/moodle-mod_unilabel#19]
When the Moodle window is small as you will have it on smartphones or tablets then a click on the boost navigation items is sent to the second layer. A click on "My Courses" does not react with the boost menu.

The screenshot shows the Boost menu and the Unilabel carousel. The picture in the Unilabel is linked to a course section. The problem comes up with and without the plugin local_boostnavigation.

<img width="697" alt="boost nav and links" src="https://user-images.githubusercontent.com/27956839/94360453-94c1c080-00ad-11eb-94bb-8dce5374dde3.png">

**Comment by grabs** [comment]
Hi Ralf,
thank you for reporting this. In the latest version for moodle 3.9 I fixed the z-index.
Best regards
Andreas

**Comment by ralf-krause** [comment]
Great! Thanks for your support!
