### ISSUE TITLE
Restore issue

### ISSUE THREAD

**Issue by behoof** [grabs/moodle-mod_unilabel#20]
Andreas,

I want to restore an unilabel and get: 

XML-bestand [tempdir]/backup//c2553b8e94a91d594f3d322cce0231e4/activities/unilabel_3439/grades.xml missing in the back-up 

On two sites both Moodle 3.8

Best regards

Bert

**Comment by grabs** [comment]
Since the version 3.11 is no longer supported, I close this issue.
Maybe the current version does not have this kind of problem.
