### ISSUE TITLE
Unilabel plugin does not work carousel for student.

### ISSUE THREAD

**Issue by cassiodruziani** [grabs/moodle-mod_unilabel#31]
Hello everything is fine? Unilabel plugin does not work carousel for student. Checking the permissions, only users and visitors can interact with the slides in the carousel (mod/unilabel:view: View unilabel). Even changing capability doesn't work. I've looked through the forums and haven't found a solution. I use version 3.11. The links are disabled. Only for the editor it works. For students the links do not work. If anyone knows the solution I would appreciate it.

**Comment by grabs** [comment]
Since the version 3.11 is no longer supported, I close this issue.
Maybe the current version does not have this kind of problem.
