### ISSUE TITLE
Label type: Grid - no description

### ISSUE THREAD

**Issue by olemde** [grabs/moodle-mod_unilabel#47]
Hi.
Is it correct that a description text of a unilabel-grid is not shown ? Or made i something wrong?

![Screenshot 2024-09-30 151119](https://github.com/user-attachments/assets/d381e3e5-eab5-420e-a153-2d00c9d5b4d4)
![Screenshot 2024-09-30 151212](https://github.com/user-attachments/assets/95717333-4390-4352-82f6-37605de480a5)
br 
Ole

**Comment by grabs** [comment]
Hi,

you have to go to "Edit content" and activate the "Show unilabel text" checkbox.
If you don't want to set this each time you create a new grid, you can activate this by default in the unilabel settings.

Best
Andreas
