### ISSUE TITLE
Not able to add hyperlinks on Collapsed text type

### ISSUE THREAD

**Issue by dcombes** [grabs/moodle-mod_unilabel#48]
Hi there

We have Unilabel version 4.4.0 and have recently upgraded to Moodle 4.4, and have found that for Collapsed Text type of Unilabel, we are not able to add any hyperlinks to our text from the Atto text editor. We can go through the process in Atto to select the text and add a link, but it isn't saved and doesn't appear in the text's HTML.

However, when doing the same process on the same Unilabel activity but changed it to Simple Text type, we are able to add a hyperlink.

It would be great if this bug for Collapsed Text type could be resolved as we use that type a lot on our Moodle.

Many thanks.
David

**Comment by grabs** [comment]
Hi David,
unfortunately I can't reproduce this at all :(.
I used the latest 4.4.4 Version of Moodle and tried Atto and TinyMCE as well. There are no problems at all. Maybe you mean something else or you have some extension on your system which prevents creating a link or displaying the hyperlink.
![unilabel-link](https://github.com/user-attachments/assets/8458aafc-2e2b-4d6e-b42d-48ad1b3cdaaa)

**Comment by dcombes** [comment]
Mmm, apologies but now I've gone in and tried again, as has my collegue who was also getting the issue, and it all seems to be working! I appreciate you checking it out so swiftly.
