### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ralf-krause** [grabs/moodle-mod_unilabel#7]
Hi Andreas,
I found that I can't install the package from the Moodle plugin database.
There is no file in the folder unilabel/type/simpletext/db/
Ralf

Überprüfen mod_unilabel ... Fehler
  [Fehler] Entpackte Datei nicht gefunden [{"file":"unilabel\/type\/simpletext\/db\/"}] 
Installation wegen einer fehlerhaften Überprüfung abgebrochen

**Comment by germanvaleroelizondo** [comment]
Same issue here,, but installing from this GitHub ZIP worked perfectly.

BUT there are many English language strings not available in AMOS.
I think you need to refresh the Moodle plugins database with the newest GitHub files.
Thanks in advance.

**Comment by grabs** [comment]
Hi, can you give me a little hint what way you went to install the plugin? I want to reproduce this. Thanks!

**Comment by grabs** [comment]
Ok, I removed the empty db folder from "unilable/type/simpletext". That should solve the problem.

**Comment by germanvaleroelizondo** [comment]
Hi,
I used a new Moodle 3.5 local server.
Installed from the Moodle plugins database. FAILED.
Downloaded from this GisHub ZIP file. SUCCESS.
I will re.try with the Moodle plugins database soon.
